# -*- coding: utf-8 -*-
"""Untitled18.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UTHriOPt1XoGNgl3sg-h2emD573kUtP0
"""

import numpy as np
import matplotlib.pyplot as plt
from numpy import linalg as LA
m1=np.reshape([1,1/np.sqrt(3)],(2,1))

V=np.reshape([1,0,0,1],(2,2))
u=np.reshape([0,0],(2,1))
f=-4
q=np.reshape([0,0],(2,1))
mu_a_1=(-m1.T@(V@q+u)+np.sqrt((m1.T@(V@q+u))**2-(q.T@V@q+2*u.T@q+f)*(m1.T@V@m1)))/(m1.T)@V@m1
mu_a_2=(-m1.T@(V@q+u)-np.sqrt((m1.T@(V@q+u))**2-(q.T@V@q+2*u.T@q+f)*(m1.T@V@m1)))/(m1.T)@V@m1
print('Possible values of mu for point A:',mu_a_1,mu_a_2)    

#setting up plot
fig = plt.figure()
ax = fig.add_subplot(111, aspect='equal')
len = 5
y = np.linspace(-4,4,len)

x=np.linspace(-6,6)
x1=np.linspace(-6,6)
xt1=np.linspace(0,np.sqrt(3))
x2=np.linspace(np.sqrt(3),2)

#plotting the circle
circle = plt.Circle((0,0),radius = 2 ,edgecolor='green',lw=1.5, fc='none',label='Circle')
plt.gca().add_patch(circle)

#naming the points
O = np.array([0,0])
A = np.array([np.sqrt(3),1])
B = np.array([2,0])

#plotting points
plt.plot(O[0], O[1], 'o',color='b')
plt.text(O[0] + 0.3, O[1] + 0.3, 'O')
plt.plot(A[0], A[1], 'o',color='b')
plt.text(A[0] + 0.3, A[1] + 0.3, 'A')
plt.plot(B[0], B[1], 'o',color='b')
plt.text(B[0] + 0.3, B[1] + 0.3, 'B')

#Plotting all lines
y1=(x1)/np.sqrt(3)
plt.axhline(y=0,color='gray')
plt.plot(x1,y1,label='$y=x/\sqrt{3}$')

# Shading the required region
yt1=(xt1)/np.sqrt(3)
plt.fill_between(xt1,0,yt1,color='pink',alpha=1)
y2 = np.sqrt(4-(x2**2))
plt.fill_between(x2,0,y2,color='pink',alpha=1)

plt.xlabel('$x-axis$')
plt.ylabel('$y-axis$')
plt.legend(loc='best')
plt.grid() 
plt.axis('equal')
plt.show()