# -*- coding: utf-8 -*-
"""Untitled25.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PeWGS-5nm4NR89JUXl7bx2GBhqorZD46
"""

import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D

# a plane is a*x+b*y+c*z=d
# [a,b,c] is the normal.

normal_1 = np.array([1, 1, 1])
d_1 = 1
normal_2 = np.array([2, 3, 4])
d_2 = 5
normal_3 = np.array([1, -1, 1])
d_3 = 0

# plane which passes through intersection of p1 and p2 and normal to p3
lamda = -(normal_1@np.transpose(normal_3))/(normal_2@np.transpose(normal_3))
normal = normal_1+lamda*(normal_2)
d = 1+lamda*5
print('value of lambda',lamda)

# create x,y
xx, yy = np.meshgrid(range(-20, 20), range(-20, 20))

#corresponding z for the planes
zz_1 = ((d) - (normal_1[0] * xx) - (normal_1[1] * yy)) *( 1 /normal_1[2])
zz_2 = ((d) - (normal_2[0] * xx) - (normal_2[1] * yy)) *( 1 /normal_2[2])
zz_3 = ((d) - (normal_3[0] * xx) - (normal_3[1] * yy)) *( 1 /normal_3[2])
zz = ((d) - (normal[0] * xx) - (normal[1] * yy)) *( 1 /normal[2])

#setting up plot
fig = plt.figure()
ax = fig.add_subplot(111,projection='3d')

#plotting planes
Plane1=ax.plot_surface(xx,zz_1,yy, color='b',alpha=0.25,label='(1 1 1)x = 1')
Plane1._facecolors2d=Plane1._facecolors3d
Plane1._edgecolors2d=Plane1._edgecolors3d

Plane2=ax.plot_surface(xx,zz_2,yy, color='b',alpha=0.25,label='(2 3 4)x = 5')
Plane2._facecolors2d=Plane2._facecolors3d
Plane2._edgecolors2d=Plane2._edgecolors3d

Plane3=ax.plot_surface(xx,zz_3,yy, color='y',alpha=0.25,label='(1 -1 1)x = 0')
Plane3._facecolors2d=Plane3._facecolors3d
Plane3._edgecolors2d=Plane3._edgecolors3d

Plane4=ax.plot_surface(xx,zz,yy, color='r',alpha=0.25,label='Plane $P$')
Plane4._facecolors2d=Plane4._facecolors3d
Plane4._edgecolors2d=Plane4._edgecolors3d

plt.xlabel('$x$');plt.ylabel('$y$')
plt.grid()
plt.legend()

plt.show()