# -*- coding: utf-8 -*-
"""Untitled31.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WK5au66lEbIXXzPTeS22wbVgvWMlRsB9
"""

import numpy as np
import matplotlib.pyplot as plt

def line_gen(A,B):
  len =10
  dim = A.shape[0]
  x_AB = np.zeros((dim,len))
  lam_1 = np.linspace(0,1,len)
  for i in range(len):
    temp1 = A + lam_1[i]*(B-A)
    x_AB[:,i]= temp1.T
  return x_AB 

y = np.linspace(-5,5,100)
x=(y*y)/8
plt.plot(x,y,label='$y^2=8x$')
plt.xlabel('$x$')
plt.ylabel('$y$')

#Plotting directrix
P=np.array([-2,-7])
Q=np.array([-2,7])
A=line_gen(P,Q)
plt.plot(A[0,:],A[1,:],label='$directrix$')

#plotting focus
plt.plot(2,0,'o',label='$focus$')
plt.text(2.2,0.2,'F(2,0)')
#plotting vertex
plt.plot(0,0,'o',label='vertex')
plt.text(0,0,' C(0,0)')

M = np.array([2,4])
N = np.array([2,-4])
#plottig Latus rectum
x_MN = line_gen(M,N)
plt.plot(x_MN[0,:],x_MN[1,:],label='$Latus rectum$')

plt.legend(loc='upper right')
plt.grid()
plt.xlim([-3,6])
plt.ylim([-7,7])
