# -*- coding: utf-8 -*-
"""code.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1p7nB5dSIehVK4k2dAVMM5G-NSCJ7WYrL
"""

import numpy as np
from scipy import linalg as lg

A = np.array([[3, -2], [4, -2]])
I = np.array([[1,0],[0,1]])
values, vectors = lg.eig(A)
print(values)

Sum = values[0] + values[1]
print(Sum)

Prod = values[0]*values[1]
print(Prod)

#The quadratic equation if sum and product are given is A^2 - (sum)A + Prod
#So, the characterisitic equation of the matrix is A^2 - A + 2I = 0

#Verification
np.linalg.matrix_power( A,2) - A + 2*I