# -*- coding: utf-8 -*-
"""Assignment_4

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1l-wt7fT-QkLyr8JCRgrFjk1Qu965-t9u
"""

import numpy as np
from matplotlib import pyplot as plt

#Generate line points
def line_gen(A,B):
  len =10
  x_AB = np.zeros((2,len))
  lam_1 = np.linspace(0,1,len)
  for i in range(len):
    temp1 = A + lam_1[i]*(B-A)
    x_AB[:,i]= temp1.T
  return x_AB

#Inputs
n = np.array([1,1]) 
c = 5
e1 = np.array([1,0]) 
e2 = np.array([0,1]) 
A = c*e1/(n@e1)
B = c*e2/(n@e2)
P = np.array([2,3])

#Generating the line
x_AB = line_gen(A,B)
#Plotting the line
plt.plot(x_AB[0,:],x_AB[1,:],label='$AB$')

#Labelling the points
plt.plot(A[0], A[1], 'o')
plt.text(A[0] * (1 + 0.1), A[1] * (1 - 0.1) , 'A')
plt.plot(B[0], B[1], 'o')
plt.text(B[0] * (1-0.3), B[1] * (1-0.1) , 'B')
plt.plot(P[0], P[1], 'o')
plt.text(P[0] * (1-0.3), P[1] * (1-0.1) , '(2,3)')

plt.xlabel('$x$')
plt.ylabel('$y$')
plt.legend(loc='best')
plt.grid()
plt.axis('equal')
plt.show()