# -*- coding: utf-8 -*-
"""Assignment_4.ipynb
Automatically generated by Colaboratory.
Original file is located at
    https://colab.research.google.com/drive/1CeLGvDcb3trqYYoZv8_NM9GcA-onDW-f
"""

#Import the libraries#
import numpy as np 
import matplotlib.pyplot as plt
from sympy import *
''' from matplotlib.pylab import rcParams '''

#To label the points # 
o = [0,0]
x = np.arange(-5,5,0.1)
x1 = np.arange(-2,1,0.1)
m = 2/9
y = (m*x)+ (85/9)
y1 = ((-9/2)*x1)
A = [-2,9]
''' 
rcParams['figure.figsize']=2,4 '''
plt.scatter(A[0],A[1],color='skyblue')
plt.scatter(o[0],o[1],color='skyblue')
plt.annotate("P", (-2, 9)) 
plt.annotate("O", (0,0))
plt.plot(x,y,color='r')
plt.plot(x1,y1,color='orange')

plt.xlabel('X - axis')
plt.ylabel('Y - axis')
plt.grid()

plt.xlim(-7,12)
plt.ylim(-7, 12)
plt.gca().set_aspect('equal', adjustable='box')
plt.draw()
